---
version: '3.6'
services:

  user-management:
    container_name: user-management
    image: user-management
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

networks:
  default:
    name: user-management-network
